// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NunitTest.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TS01 Basic")]
    [NUnit.Framework.CategoryAttribute("PBI531869")]
    [NUnit.Framework.CategoryAttribute("F529235")]
    [NUnit.Framework.CategoryAttribute("DepHR_HRAdmin_PayClass_TS01Basic")]
    [NUnit.Framework.CategoryAttribute("ui")]
    [NUnit.Framework.CategoryAttribute("Team_HR_UI")]
    [NUnit.Framework.CategoryAttribute("HR_UI_HR3")]
    [NUnit.Framework.CategoryAttribute("Contributor_Uddhav")]
    [NUnit.Framework.CategoryAttribute("HRAdmin")]
    [NUnit.Framework.CategoryAttribute("HR3_UI_HRAdmin")]
    [NUnit.Framework.CategoryAttribute("HRAdmin_PayClass")]
    [NUnit.Framework.CategoryAttribute("HRPayClass")]
    [NUnit.Framework.CategoryAttribute("HR_UI_General")]
    public partial class TS01BasicFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "PBI531869",
                "F529235",
                "DepHR_HRAdmin_PayClass_TS01Basic",
                "ui",
                "Team_HR_UI",
                "HR_UI_HR3",
                "Contributor_Uddhav",
                "HRAdmin",
                "HR3_UI_HRAdmin",
                "HRAdmin_PayClass",
                "HRPayClass",
                "HR_UI_General"};
        
#line 1 "TS01 Basic.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TS01 Basic", null, ProgrammingLanguage.CSharp, new string[] {
                        "PBI531869",
                        "F529235",
                        "DepHR_HRAdmin_PayClass_TS01Basic",
                        "ui",
                        "Team_HR_UI",
                        "HR_UI_HR3",
                        "Contributor_Uddhav",
                        "HRAdmin",
                        "HR3_UI_HRAdmin",
                        "HRAdmin_PayClass",
                        "HRPayClass",
                        "HR_UI_General"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 24
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "USEmployeeManager2"});
#line 26
 testRunner.Given("system has existing employees with table", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role REF",
                        "Name",
                        "Copy From"});
            table2.AddRow(new string[] {
                        "1",
                        "AT Role",
                        "Retail Manager"});
#line 30
 testRunner.Given("system has data in Roles with table", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role REF",
                        "Name",
                        "Value",
                        "Path"});
            table3.AddRow(new string[] {
                        "1",
                        "Pay Class",
                        "Checked",
                        "HR Admin > HR Admin"});
#line 33
 testRunner.And("system has data in Role Features with table", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "User Login ID",
                        "Role REF"});
            table4.AddRow(new string[] {
                        "USEmployeeManager2",
                        "1"});
#line 36
 testRunner.And("system has data in Users with Roles with table", ((string)(null)), table4, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC01 - Add pay class")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        [NUnit.Framework.CategoryAttribute("HR_UI_Sanity")]
        public virtual void SC01_AddPayClass()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass",
                    "HR_UI_Sanity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC01 - Add pay class", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
#line 46
 testRunner.When("USEmployeeManager2 logs in as AT Role role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 48
 testRunner.And("navigates to HR Admin > Pay Class page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code",
                            "Pay Class Group"});
                table5.AddRow(new string[] {
                            "1",
                            "TATPay1",
                            "TATPayClass1",
                            "TATPC1",
                            "Full-time"});
#line 50
 testRunner.And("adds and edits data in Pay Class grid with table", ((string)(null)), table5, "And ");
#line hidden
#line 53
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
 testRunner.Then("changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code",
                            "Pay Class Group"});
                table6.AddRow(new string[] {
                            "1",
                            "TATPay1",
                            "TATPayClass1",
                            "TATPC1",
                            "Full-time"});
#line 55
 testRunner.And("data should be displayed in Pay Class grid with table", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
