// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NunitTest.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TS01 General")]
    [NUnit.Framework.CategoryAttribute("PBI531869")]
    [NUnit.Framework.CategoryAttribute("F529235")]
    [NUnit.Framework.CategoryAttribute("DepHR_HRAdmin_PayClass_TS01General")]
    [NUnit.Framework.CategoryAttribute("ui")]
    [NUnit.Framework.CategoryAttribute("Team_HR_UI")]
    [NUnit.Framework.CategoryAttribute("HR_UI_HR3")]
    [NUnit.Framework.CategoryAttribute("Contributor_Adiilah")]
    [NUnit.Framework.CategoryAttribute("HRAdmin")]
    [NUnit.Framework.CategoryAttribute("HR3_UI_HRAdmin")]
    [NUnit.Framework.CategoryAttribute("HRAdmin_PayClass")]
    [NUnit.Framework.CategoryAttribute("HRPayClass")]
    [NUnit.Framework.CategoryAttribute("HR_UI_General")]
    public partial class TS01GeneralFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "PBI531869",
                "F529235",
                "DepHR_HRAdmin_PayClass_TS01General",
                "ui",
                "Team_HR_UI",
                "HR_UI_HR3",
                "Contributor_Adiilah",
                "HRAdmin",
                "HR3_UI_HRAdmin",
                "HRAdmin_PayClass",
                "HRPayClass",
                "HR_UI_General"};
        
#line 1 "TS01 General.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TS01 General", null, ProgrammingLanguage.CSharp, new string[] {
                        "PBI531869",
                        "F529235",
                        "DepHR_HRAdmin_PayClass_TS01General",
                        "ui",
                        "Team_HR_UI",
                        "HR_UI_HR3",
                        "Contributor_Adiilah",
                        "HRAdmin",
                        "HR3_UI_HRAdmin",
                        "HRAdmin_PayClass",
                        "HRPayClass",
                        "HR_UI_General"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 24
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table7.AddRow(new string[] {
                        "USEmployeeManager2"});
#line 26
 testRunner.Given("system has existing employees with table", ((string)(null)), table7, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Locations",
                        "Primary",
                        "Start Date",
                        "End Date"});
            table8.AddRow(new string[] {
                        "ATOnSiteDeptUSA",
                        "Checked",
                        "-3 years",
                        ""});
#line 29
 testRunner.And("USEmployeeManager2 has existing data using SQL Clear Insert in Security Settings " +
                    "> Location Access grid with table", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role REF",
                        "Name",
                        "Copy From"});
            table9.AddRow(new string[] {
                        "1",
                        "AT Role",
                        "Retail Manager"});
#line 33
 testRunner.Given("system has data in Roles with table", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Role REF",
                        "Name",
                        "Value",
                        "Path"});
            table10.AddRow(new string[] {
                        "1",
                        "Pay Class",
                        "Checked",
                        "HR Admin > HR Admin"});
#line 36
 testRunner.And("system has data in Role Features with table", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "User Login ID",
                        "Role REF"});
            table11.AddRow(new string[] {
                        "USEmployeeManager2",
                        "1"});
#line 40
 testRunner.And("system has data in Users with Roles with table", ((string)(null)), table11, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC01 Open Pay Class page and check availability of the control and control elemen" +
            "ts")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        public virtual void SC01OpenPayClassPageAndCheckAvailabilityOfTheControlAndControlElements()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC01 Open Pay Class page and check availability of the control and control elemen" +
                    "ts", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
#line 48
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
 testRunner.Then("should be able to add data in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
 testRunner.And("should be able to read data in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
 testRunner.And("should be able to copy data in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
 testRunner.And("should be able to delete data in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
 testRunner.And("should be able to localize data in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
 testRunner.And("Problems pane should NOT be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
 testRunner.And("first row should be selected in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Header 1",
                            "Header 2",
                            "Header 3",
                            "Header 4",
                            "Header 5",
                            "Header 6",
                            "Header 7"});
                table12.AddRow(new string[] {
                            "Name",
                            "Description",
                            "Default Weekly Hours",
                            "Reference Code",
                            "Sort Order",
                            "Pay Class Group",
                            "Ledger Code"});
#line 56
 testRunner.And("headers data should be displayed in Pay Class grid with table", ((string)(null)), table12, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC02 - Check add pay class empty row validation")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        public virtual void SC02_CheckAddPayClassEmptyRowValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC02 - Check add pay class empty row validation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
#line 64
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
 testRunner.And("adds data in Pay Class grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
 testRunner.Then("Problems pane should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Message"});
                table13.AddRow(new string[] {
                            "Name - Value is required"});
                table13.AddRow(new string[] {
                            "Reference Code - Value is required"});
#line 68
 testRunner.And("errors should be printed in Problems pane with table", ((string)(null)), table13, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC03 - Check duplicate pay class reference code validation")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BS_CleanPayClass")]
        [NUnit.Framework.CategoryAttribute("HR_UI_Sanity")]
        public virtual void SC03_CheckDuplicatePayClassReferenceCodeValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BS_CleanPayClass",
                    "HR_UI_Sanity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC03 - Check duplicate pay class reference code validation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
#line 79
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table14.AddRow(new string[] {
                            "1",
                            "TATPay1",
                            "TATPayClass1",
                            "TATPC1"});
                table14.AddRow(new string[] {
                            "2",
                            "TATPay2",
                            "TATPayClass2",
                            "TATPC1"});
#line 80
 testRunner.And("adds and edits data in Pay Class grid with table", ((string)(null)), table14, "And ");
#line hidden
#line 84
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
 testRunner.Then("Problems pane should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Message"});
                table15.AddRow(new string[] {
                            "Reference Code - Value is not unique"});
#line 86
 testRunner.And("errors should be printed in Problems pane with table", ((string)(null)), table15, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC04 - Add several pay class records")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        [NUnit.Framework.CategoryAttribute("HR_UI_Sanity")]
        public virtual void SC04_AddSeveralPayClassRecords()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass",
                    "HR_UI_Sanity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC04 - Add several pay class records", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
#line 96
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table16.AddRow(new string[] {
                            "3",
                            "TATPay3",
                            "TATPayClass3",
                            "TATPC3"});
                table16.AddRow(new string[] {
                            "4",
                            "TATPay4",
                            "TATPayClass4",
                            "TATPC4"});
                table16.AddRow(new string[] {
                            "5",
                            "TATPay5",
                            "TATPayClass5",
                            "TATPC5"});
#line 97
 testRunner.And("adds and edits data in Pay Class grid with table", ((string)(null)), table16, "And ");
#line hidden
#line 102
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 103
 testRunner.Then("changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table17.AddRow(new string[] {
                            "3",
                            "TATPay3",
                            "TATPayClass3",
                            "TATPC3"});
                table17.AddRow(new string[] {
                            "4",
                            "TATPay4",
                            "TATPayClass4",
                            "TATPC4"});
                table17.AddRow(new string[] {
                            "5",
                            "TATPay5",
                            "TATPayClass5",
                            "TATPC5"});
#line 104
 testRunner.And("data should be displayed in Pay Class grid with table", ((string)(null)), table17, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC05 - Delete pay class record")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        public virtual void SC05_DeletePayClassRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC05 - Delete pay class record", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 114
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Reference Code"});
                table18.AddRow(new string[] {
                            "TATPay6",
                            "TATPayClass6",
                            "TATPC6"});
#line 115
 testRunner.Given("system has configuration data in HR Admin > Pay Class with table", ((string)(null)), table18, "Given ");
#line hidden
#line 118
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Reference Code"});
                table19.AddRow(new string[] {
                            "TATPay6",
                            "TATPayClass6",
                            "TATPC6"});
#line 119
 testRunner.And("deletes data in Pay Class grid with table", ((string)(null)), table19, "And ");
#line hidden
#line 122
 testRunner.And("confirms in Please Confirm dialog if exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 123
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 124
 testRunner.Then("changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
 testRunner.And("Problems pane should NOT be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC06 - Copy pay class record")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        public virtual void SC06_CopyPayClassRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC06 - Copy pay class record", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 131
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table20.AddRow(new string[] {
                            "7",
                            "TATPay7",
                            "TATPayClass7",
                            "TATPC7"});
#line 132
 testRunner.Given("system has configuration data in HR Admin > Pay Class with table", ((string)(null)), table20, "Given ");
#line hidden
#line 135
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code",
                            "New REF"});
                table21.AddRow(new string[] {
                            "7",
                            "TATPay7Copy1",
                            "TATPayClass7Copy1",
                            "TATPC7Copy1",
                            "8"});
#line 136
 testRunner.And("copies and edits data in Pay Class grid with table", ((string)(null)), table21, "And ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table22.AddRow(new string[] {
                            "7",
                            "TATPay7",
                            "TATPayClass7",
                            "TATPC7"});
                table22.AddRow(new string[] {
                            "8",
                            "TATPay7Copy1",
                            "TATPayClass7Copy1",
                            "TATPC7Copy1"});
#line 139
 testRunner.Then("data should be displayed in Pay Class grid with table", ((string)(null)), table22, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC07 - Check localize dialog")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        public virtual void SC07_CheckLocalizeDialog()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC07 - Check localize dialog", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 148
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Reference Code"});
                table23.AddRow(new string[] {
                            "TATPay8",
                            "TATPayClass8",
                            "TATPC8"});
#line 149
 testRunner.Given("system has configuration data in HR Admin > Pay Class with table", ((string)(null)), table23, "Given ");
#line hidden
#line 152
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Reference Code"});
                table24.AddRow(new string[] {
                            "TATPay8",
                            "TATPayClass8",
                            "TATPC8"});
#line 153
 testRunner.And("localizes data in Pay Class grid with table", ((string)(null)), table24, "And ");
#line hidden
#line 156
 testRunner.Then("Pay Class dialog should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC08 - Delete pay class which is in use")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        public virtual void SC08_DeletePayClassWhichIsInUse()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC08 - Delete pay class which is in use", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 162
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
#line 163
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Reference Code"});
                table25.AddRow(new string[] {
                            "FT",
                            "Full Time",
                            "FT"});
#line 164
 testRunner.And("deletes data in Pay Class grid with table", ((string)(null)), table25, "And ");
#line hidden
#line 167
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 168
 testRunner.Then("Problems pane should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Message"});
                table26.AddRow(new string[] {
                            "FT - Cannot be deleted because it is already in use"});
#line 169
 testRunner.And("errors should be printed in Problems pane with table", ((string)(null)), table26, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SC09 - Edit pay class record")]
        [NUnit.Framework.CategoryAttribute("HR_UI_P3")]
        [NUnit.Framework.CategoryAttribute("HR3_VB34")]
        [NUnit.Framework.CategoryAttribute("BSAS_CleanPayClass")]
        public virtual void SC09_EditPayClassRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "HR_UI_P3",
                    "HR3_VB34",
                    "BSAS_CleanPayClass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SC09 - Edit pay class record", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 177
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table27.AddRow(new string[] {
                            "3",
                            "TATPay3",
                            "TATPayClass3",
                            "TATPC3"});
#line 178
 testRunner.Given("system has configuration data in HR Admin > Pay Class with table", ((string)(null)), table27, "Given ");
#line hidden
#line 181
 testRunner.When("USEmployeeManager2 logs in as AT Role role and navigates to HR Admin > Pay Class " +
                        "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "DFPayClass REF",
                            "Name",
                            "Description",
                            "Reference Code"});
                table28.AddRow(new string[] {
                            "3",
                            "TATPay3",
                            "TATPayClass3_Modified",
                            "TATPC3_Modified"});
#line 182
 testRunner.And("edits data in Pay Class grid with table", ((string)(null)), table28, "And ");
#line hidden
#line 185
 testRunner.And("saves changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 186
 testRunner.Then("changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Reference Code"});
                table29.AddRow(new string[] {
                            "TATPay3",
                            "TATPayClass3_Modified",
                            "TATPC3_Modified"});
#line 187
 testRunner.And("data should be displayed in Pay Class grid with table", ((string)(null)), table29, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
